services:

  # only redis
  # redis:
  #   image: redis:7-alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   command: ["redis-server", "--appendonly", "yes"]

  
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: my-redis-db

volumes:
  redis_data:
  redisinsight_data:
  mongo_data: